### ISSUE TITLE
Cannot execute queries from the "Browse" tab

### ISSUE THREAD

**Issue by naifwonder** [orientechnologies/orientdb-studio#218]
Whenever I try to run any query, I get the error below then nothing happens:

ReferenceError: $ is not defined
    at Spinner.spinner.start (http://localhost:9000/scripts/services/spinner-service.js:45:9)
    at k.$scope.query (http://localhost:9000/scripts/controllers/database-controller.js:146:15)
    at http://localhost:9000/components/angular/angular.min.js:175:190
    at http://localhost:9000/components/angular/angular.min.js:192:165
    at k.$eval (http://localhost:9000/components/angular/angular.min.js:112:32)
    at k.$apply (http://localhost:9000/components/angular/angular.min.js:112:310)
    at HTMLButtonElement.<anonymous> (http://localhost:9000/components/angular/angular.min.js:192:147)
    at http://localhost:9000/components/angular/angular.min.js:31:225
    at Array.forEach (native)
    at q (http://localhost:9000/components/angular/angular.min.js:7:280)

**Comment by maggiolo00** [comment]
Should be fixed in develop

**Comment by lvca** [comment]
@naifwonder  I'm closing the issue waiting for you confirm. In case please reopen it.
