### ISSUE TITLE
NPE from OObjectProxyMethodHandler

### ISSUE THREAD

**Issue by PavelNiedoba** [orientechnologies/orientdb-studio#225]
I'm using 2.0.-M3

  getting db this way: (remote:/bbb)
  OObjectDatabaseTx db;
  db.setAutomaticSchemaGeneration(true);
  db.getEntityManager().registerEntityClasses("mypkg.persisted*");

  when I run query:
  select from User where loginName='root'
  I get User object correctly returned
 but when I call
  user.getPassword()

 get NPE
java.lang.NullPointerException
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getDocFieldValue(OObjectProxyMethodHandler.java:362)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getValue(OObjectProxyMethodHandler.java:351)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getValue(OObjectProxyMethodHandler.java:288)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.manageGetMethod(OObjectProxyMethodHandler.java:277)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.invoke(OObjectProxyMethodHandler.java:103)
	at mypkg.persisted.User_$$_javassist_0.getPassword(User_$$_javassist_0.java)

I can see User in studio correctly. 

exactly same code worked with 1.7.9 and 1.7.10, but with 1.7.9. i have connection pool problems, 1.7.10 fails in order by rid desc.
is 2.0.-M3 production ready ?

**Comment by lvca** [comment]
We released 2.0 as production ready. Please could you test with that version?

**Comment by PavelNiedoba** [comment]
Hallo 

  I did test with 2.0, but I experience another exception even before that. I opened another issue:
https://github.com/orientechnologies/orientdb-studio/issues/226

 When I remove indexes, I get same exception like in 2.0.M3



Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getDocFieldValue(OObjectProxyMethodHandler.java:362)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getValue(OObjectProxyMethodHandler.java:351)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getValue(OObjectProxyMethodHandler.java:288)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.manageGetMethod(OObjectProxyMethodHandler.java:277)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.invoke(OObjectProxyMethodHandler.java:103)
	at ....persisted.User_$$_javassist_0.getPassword(User_$$_javassist_0.java)


I tried corresponding query in studio
select password from User where loginName='root'

and it works as expected

**Comment by PavelNiedoba** [comment]
Well this issue should be rather in orientdb, not orientdb-studio

**Comment by maggiolo00** [comment]
@PavelNiedoba 
yes :+1: 
could you open it on orientdb?

**Comment by PavelNiedoba** [comment]
created issue in orientdb: https://github.com/orientechnologies/orientdb/issues/3447
