### ISSUE TITLE
Error in OrientDB logs (Missing Favico.ico)

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb-studio#228]
```
2015-02-06 11:17:23:930 INFO  OrientDB Server v2.1-SNAPSHOT is active. [OServer]
2015-02-06 11:19:38:400 WARNING path variable points to 'src/site' but it doesn't exists [OServerCommandGetStaticContent]
2015-02-06 11:19:38:401 WARNING path variable points to 'src/site' but it isn't a directory [OServerCommandGetStaticContent]Error on loading resource /favicon.ico
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.flush(OHttpResponse.java:507)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.sendStream(OHttpResponse.java:440)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.sendStream(OHttpResponse.java:401)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetStaticContent.execute(OServerCommandGetStaticContent.java:137)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:200)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:600)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
```

**Comment by lvca** [comment]
I think this has been resolved in 2.0.5.
