### ISSUE TITLE
Remove Edge Error - java.lang.NullPointerException

### ISSUE THREAD

**Issue by sunra** [orientechnologies/orientdb-studio#306]
used *orientdb-community-2.0.12*

# Try removing Edge, One of Vertexes it connects removed earlier. 

Edge:
```json
{
    "result": [
        {
            "@type": "d",
            "@rid": "#17:2",
            "@version": 9,
            "@class": "isAuthor",
            "out": "#13:1",
            "in": "#12:20",
            "@fieldTypes": "out=x,in=x"
        }
    ],
    "notification": "Query executed in 0.043 sec. Returned 1 record(s)"
}
```
select from #12:20:
```
Returned 0 record(s)
```
select from #13:1
```json
{
    "result": [
        {
            "@type": "d",
            "@rid": "#13:1",
            "@version": 17,
            "@class": "User",
            "is_active": true,
            "symfony_login": "admin",
            "displayName": "AlexBel",
            "ls_user_id": "1",
            "out_isAuthor": [
                "#17:2"
            ],
            "@fieldTypes": "out_isAuthor=g"
        }
    ],
    "notification": "Query executed in 0.045 sec. Returned 1 record(s)"
}
```

## in Studio
return:

```
 java.lang.NullPointerException
```

log:
```
2015-07-11 04:52:05:577 SEVERE Internal server error:
java.lang.NullPointerException [ONetworkProtocolHttpDb]
```

## from SQL

return:
```
 com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.DELETE EDGE #17:2
```

log:
```
Sent run-time exception to the client /127.0.0.1:33264: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.DELETE EDGE #17:2
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.DELETE EDGE #17:2
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1200)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1183)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1183)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:390)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.NullPointerException
        at com.tinkerpop.blueprints.impls.orient.OrientEdge.remove(OrientEdge.java:420)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteEdge$1.call(OCommandExecutorSQLDeleteEdge.java:169)
        at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:123)
        at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:142)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteEdge.execute(OCommandExecutorSQLDeleteEdge.java:164)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1194)
        ... 6 more

```

**Comment by lvca** [comment]
How did you remove the vertex earlier?

**Comment by sunra** [comment]
Most possible i use "Truncate class Topic"

**Comment by lvca** [comment]
Truncate class didn't remove edges. In 2.1 OrientDB throws an exception but you can always use "UNSAFE" to do that. Use rather `delete vertex`.
