### ISSUE TITLE
binary data uploading problem.

### ISSUE THREAD

**Issue by DThink** [orientechnologies/orientdb-studio#422]
hi if i try to upload a png image by orientdb studio i receive in the client side this error

```
scripts.js:97 Error: [$compile:nodomevents] http://errors.angularjs.org/1.2.18/$compile/nodomevents
    at http://192.168.0.3:2480/studio/scripts/scripts.js:11:450
    at pre (http://192.168.0.3:2480/studio/scripts/scripts.js:68:24)
    at M (http://192.168.0.3:2480/studio/scripts/scripts.js:59:6)
    at f (http://192.168.0.3:2480/studio/scripts/scripts.js:52:142)
    at http://192.168.0.3:2480/studio/scripts/scripts.js:51:258
    at link (http://192.168.0.3:2480/studio/scripts/scripts.js:199:479)
    at M (http://192.168.0.3:2480/studio/scripts/scripts.js:59:211)
    at f (http://192.168.0.3:2480/studio/scripts/scripts.js:52:142)
    at http://192.168.0.3:2480/studio/scripts/scripts.js:51:258
    at http://192.168.0.3:2480/studio/scripts/scripts.js:53:97 <input type="file" class="form-control ng-scope ng-pristine ng-valid" ng-required="isRequired(header)" ng-change="" onchange="angular.element(this).scope().handleFile('{{ header  }}',this.files)" ng-model="doc[header]">(anonymous function) @ scripts.js:97
http://192.168.0.3:2480/uploadSingleFile/MyApp Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```
and in the server side this error

```
2016-12-03 11:57:28:777 SEVER Internal server error:
com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content for record #5:10
	DB name="MyApp"
--> java.lang.IllegalArgumentException: Invalid field name '{{ header  }}'. Character ' ' is invalid [ONetworkProtocolHttpDb]
```

how can i solve this?

**Comment by lvca** [comment]
How do you send the image?

**Comment by DThink** [comment]
by the orientdb studio graphic dashboard

![ousercrop](https://cloud.githubusercontent.com/assets/18085313/20887938/fd00900e-bafc-11e6-8d83-d365a3cc3986.jpg)

**Comment by maggiolo00** [comment]
hi @DThink 

it's an old issue. ODB Http does not handle well Multipart Request. We have in our roadmap the new HTTP server, probably jetty. That allow Studio to post images

**Comment by lvca** [comment]
We already have issues to support uploading in our HTTP server.
