### ISSUE TITLE
Error Deserializing Record

### ISSUE THREAD

**Issue by mdpendergrass** [orientechnologies/orientdb-studio#444]
I have a small database with about 90 vertexes in it.  For some reason, this particular node keeps throwing this exception.  It only happens after I build the links from the other nodes. This particular node is a terminal node in the graph for many paths (41 edges point into this node).

Before I build the edges, I can read the node just fine. After, I build the edges, I get this exception. I have rebuilt the database several times.  I can read other terminal nodes with out problems.  This single one seems to be the trouble maker.

I am using 2.2.15 but it was also happening with 2.2.14

I noticed the statement `send this data for debugging` so here it is :-)

```
2017-01-29 23:28:41:174 WARNI Error deserializing record with id #38:19 send this data for debugging: AChkYXRhdHlwZV9kZWZpbml0aW9ucw5pbl91c2VzAAAARxYlAAAAZAhuYW1lAAAAZwccbWF4aW11bV9sZW5ndGgAAABzAQAAGmfmXQAAAPoAAAAAAAAAAAAAEAAAAAAoAAAAAARTVBZTdHJpbmcgRGF0YY4D  [ORecordSerializerBinary]Fetching error on record #38:19
com.orientechnologies.orient.core.exception.ODatabaseException: The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:51)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.<init>(OSBTreeRidBag.java:61)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.fromStream(ORidBag.java:310)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:475)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:275)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:80)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1851)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2620)
	at com.orientechnologies.orient.core.record.impl.ODocument.fieldNames(ODocument.java:742)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecord(OFetchHelper.java:290)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:76)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.toString(ORecordSerializerJSON.java:344)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toString(ORecordSerializerStringAbstract.java:672)
	at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:191)
	at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:187)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
	at orientdb.core$ODocument__GT_map.invokeStatic(core.clj:101)
	at orientdb.core$ODocument__GT_map.invoke(core.clj:100)
	at clojure.core$mapv$fn__9368.invoke(core.clj:6788)
	at clojure.core.protocols$fn__9143.invokeStatic(protocols.clj:167)
	at clojure.core.protocols$fn__9143.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__9098$G__9093__9107.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__9120.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__9120.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__9072$G__9067__9085.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6704)
	at clojure.core$mapv.invokeStatic(core.clj:6779)
	at clojure.core$mapv.invoke(core.clj:6779)
	at orientdb.core$query.invokeStatic(core.clj:114)
	at orientdb.core$query.invoke(core.clj:112)
	at user$eval11727.invokeStatic(form-init2697171359453008819.clj:53)
	at user$eval11727.invoke(form-init2697171359453008819.clj:53)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6941)
	at clojure.core$eval.invokeStatic(core.clj:3187)
	at clojure.core$eval.invoke(core.clj:3183)
	at clojure.main$repl$read_eval_print__9983$fn__9986.invoke(main.clj:242)
	at clojure.main$repl$read_eval_print__9983.invoke(main.clj:242)
	at clojure.main$repl$fn__9992.invoke(main.clj:260)
	at clojure.main$repl.invokeStatic(main.clj:260)
	at clojure.main$repl.doInvoke(main.clj:176)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__827.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1963)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1963)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:85)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:55)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__872$fn__875.invoke(interruptible_eval.clj:222)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__867.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by laa** [comment]
Hi @mdpendergrass , did you try to call "ODatabaseRecordThreadLocal.INSTANCE.set(db);" before calling the method ?

**Comment by mdpendergrass** [comment]
Yes. I have tried both calling `.set` on the ODatabaseRecordThreadLocal.INSTANCE  as well as calling the `activateOnThread` as mentioned in the docs. The interesting thing is that the error is thrown both while doing a select of a single record as well as while doing a select of all the records in the class. When doing the select of all the records (there are only 90 recrods in this class) 89 read in just fine with no errors at all. Works beautifully except when I try to read this one. This one fails. Now, before I create the edges, I can read it fine. Once I create the edges, I can't read it anymore. I can read any other record from this class after creating the edges, just not this one.

**Comment by laa** [comment]
@mdpendergrass could you send me database and rid of the record in question ?

**Comment by mdpendergrass** [comment]
Done. Sent to your email address

**Comment by laa** [comment]
Hi @mdpendergrass , I opened your database using simple Java application
```
  ODatabaseDocumentTx db = new ODatabaseDocumentTx("plocal:../../hl7db");
    db.open("admin", "admin");
    System.out.println(db.load(new ORecordId("#36:42")));
    db.close();
```
As result I got 
```
datatype_definitions#36:42{in_uses:[...],type:ST,name:String Data,maximum_length:199}
```

So as you can see all data are loaded without a problem.
I suppose that problem, not in DB implementation but clojure integration. 
Anyway I suppose you agree that we can confirm that it is not core bug at all.

**Comment by mdpendergrass** [comment]
I am not so convinced. You are using a different way of loading the record that I am. I will try your code and see if I can put together a java sequence that illustrates the issue more clearly. I will try to have you an example in java rather than clojure as soon as I can. I appreciate your investigation into this issue.

**Comment by mdpendergrass** [comment]
Ok, I found the issue and this is indeed NOT a bug. Thanks for your help and for looking into this.
